# Generated by Django 4.2.4 on 2023-08-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_pose',
            new_name='guest_can_pause',
        ),
    ]
