# Generated by Django 4.2.5 on 2023-09-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='GG', max_length=8, unique=True),
        ),
    ]
